# 04. 최적화

목적함수의 결과값을 최적화하는 변수를 찾는 알고리즘

최적의 가중치에서는 오차가 가장 작으며 최적의 가중치에서 멀어질수록 오차가 커지는 것을 확인할 수 있다

얼마나 이동해야하는지 알 수 없기 때문에 최적화 방법을 사용한다

### 경사 하강법

함수의 기울기가 낮은 곳으로 계속 이동시켜 극값에 도달할 때 까지 반복하는 알고리즘

기울기가 0을 가지게 되는 가중치를 찾을 때 까지 반복하게 된다

### 학습률

가중치를 갱신할 때 a를 곱해 가중치 결과를 조정한다

이 때 a를 학습률이라고 한다 

초기값을 임의로 설정한다

적절하지 않은 학습률은 너무 많은 반복이 필요하거나 아무리 반복해도 최적의 해를 찾기 어려울 수 있다

최적화 알고리즘은 경사하강법 이외에도 모멘텀, Adagrad,Adam 등이 있다 보통 Adam을 쓴다 최적화 한 값을 찾아주기 때문

### 단순 선형 회귀

In [7]:
import torch
from torch import nn
from torch import optim

# 데이터 선언
x = torch.FloatTensor([
    [1], [2], [3], [4], [5], [6], [7], [8], [9], [10],
    [11], [12], [13], [14], [15], [16], [17], [18], [19], [20],
    [21], [22], [23], [24], [25], [26], [27], [28], [29], [30]
])
y = torch.FloatTensor([
    [0.94], [1.98], [2.88], [3.92], [3.96], [4.55], [5.64], [6.3], [7.44], [9.1],
    [8.46], [9.5], [10.67], [11.16], [14], [11.83], [14.4], [14.25], [16.2], [16.32],
    [17.46], [19.8], [18], [21.34], [22], [22.5], [24.57], [26.04], [21.6], [28.8]
])

# 모델 선언
model = nn.Linear(1, 1)

# 손실함수 선언
criterion = nn.MSELoss()

# 최적화 선언
optimizer = optim.SGD(model.parameters(), lr=0.001)

for epoch in range(10000):
    output = model(x)
    cost = criterion(output, y)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[0.8538]], requires_grad=True), Parameter containing:
tensor([0.0748], requires_grad=True)], Cost : 1.434
Epoch : 2000, Model : [Parameter containing:
tensor([[0.8633]], requires_grad=True), Parameter containing:
tensor([-0.1181], requires_grad=True)], Cost : 1.396
Epoch : 3000, Model : [Parameter containing:
tensor([[0.8692]], requires_grad=True), Parameter containing:
tensor([-0.2382], requires_grad=True)], Cost : 1.382
Epoch : 4000, Model : [Parameter containing:
tensor([[0.8728]], requires_grad=True), Parameter containing:
tensor([-0.3129], requires_grad=True)], Cost : 1.376
Epoch : 5000, Model : [Parameter containing:
tensor([[0.8751]], requires_grad=True), Parameter containing:
tensor([-0.3593], requires_grad=True)], Cost : 1.374
Epoch : 6000, Model : [Parameter containing:
tensor([[0.8766]], requires_grad=True), Parameter containing:
tensor([-0.3883], requires_grad=True)], Cost : 1.373
Epoch : 7000, Model : [Parameter containi