# 05. 데이터 세트와 데이터 로더

### 데이터 세트

데이터의 집합을 의미

입력값(X)와 결괏값(Y)에 대한 정보를 제공하거나 데이터 샘플을 저장하고 정답을 저장하는 기능을 제공일련의 데이터 묶음을 제공

일반적으로 데이터베이스와 테이블과 같은 형태로 구성

### 데이터 로더

데이터 세트에 저장된 데이터를 어떠한 방식으로 불러와 활용할 지 정의

배치 크기(batch_size), 데이터 순서 변경(shuffle), 데이터 로드 프로세스 수(num_workers) 등의 기능을 제공한다

배치 크기(batch_size) : 학습에 사용되는 데이터의 수가 매우 많아  한 번의 에폭에서 모든 데이터를 메모리에 올릴 수 없을 때 데이터를 나누는 역할, 전체 데이터를 10개의 배치 크기로 나누었을 때 한번 학습 시 10개의 배치를 다 돌면 1회 에폭으로 카운트됨

데이터 순서 변경 : 모델이 데이터 간의 관계가 아닌, 데이터의 순서로 학습되는 것을 방지하고자 수행하는 기능, 데이터 샘플과 정답의 매핑 관계는 변경되지 않으며, 행의 순서를 변경하는 개념

데이터 로드 프로세스 수 : 데이터를 불러올 때 사용할 프로세스의 개수를 의미, 학습을 제외한 코드에서는 데이터를 불러오는 데에 가장 시간이 오래 소요되는데, 이를 최소화 하고자 조절 가능





### 다중 선형 회귀

In [2]:
import torch
from torch import nn
from torch import optim
from torch.utils.data import TensorDataset, DataLoader 


train_x = torch.FloatTensor([
    [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]
])
train_y = torch.FloatTensor([
    [0.1, 1.5], [1, 2.8], [1.9, 4.1], [2.8, 5.4], [3.7, 6.7], [4.6, 8]
])


train_dataset = TensorDataset(train_x, train_y)
train_dataloader = DataLoader(train_dataset, batch_size=2, shuffle=True, drop_last=True)

model = nn.Linear(2, 2, bias=True)
criterion = nn.MSELoss()
lr = 0.001

optimizer = optim.SGD(model.parameters(), lr=lr)

for epoch in range(20000):
    cost = 0.0
    
    for batch in train_dataloader:
        x, y = batch
        output = model(x)
        
        loss = criterion(output, y)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        cost += loss

    cost = cost / len(train_dataloader)
    
    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[0.3568, 0.4532],
        [0.2948, 0.9492]], requires_grad=True), Parameter containing:
tensor([-0.8740, -0.5132], requires_grad=True)], Cost : 0.019
Epoch : 2000, Model : [Parameter containing:
tensor([[0.4482, 0.4059],
        [0.3517, 0.9197]], requires_grad=True), Parameter containing:
tensor([-1.0128, -0.5996], requires_grad=True)], Cost : 0.005
Epoch : 3000, Model : [Parameter containing:
tensor([[0.4948, 0.3818],
        [0.3807, 0.9048]], requires_grad=True), Parameter containing:
tensor([-1.0834, -0.6435], requires_grad=True)], Cost : 0.001
Epoch : 4000, Model : [Parameter containing:
tensor([[0.5185, 0.3695],
        [0.3955, 0.8971]], requires_grad=True), Parameter containing:
tensor([-1.1194, -0.6659], requires_grad=True)], Cost : 0.000
Epoch : 5000, Model : [Parameter containing:
tensor([[0.5306, 0.3633],
        [0.4030, 0.8932]], requires_grad=True), Parameter containing:
tensor([-1.1378, -0.6773], requires_grad=True)]